### ISSUE TITLE
Make state transitions atomic

### ISSUE THREAD

**Issue by muhrin** [aiidateam/plumpy#1]
The `Process` state transitions are performed by `perform_x` methods where x is the new state.  However, during the execution of the previous state, changes may be made to the internal state of the process instance which make it look like it is in a state in between the two.  One way to solve this is to make the `perform_`  methods do the transition, thereby becoming the 'atom' of a state transition.  Variables that it needs to use can be parameters which are bound using `partial` and then it is the `perform_` function that alters the internal variables of the process.

.. note: This is also a good opportunity to check that the on_process_x events are being sent at the right point.

**Comment by sphuber** [comment]
This has been taken care of in the `murhin/plumpy` fork
