### ISSUE TITLE
Failed occationally TestRemoteProcessThreadController::test_kill

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/plumpy#109]
The unittest `test/rmq/test_process_comms.py::TestRemoteProcessThreadController::test_kill`:
https://github.com/aiidateam/plumpy/blob/d62380e7fc449bcf812d7a2f80b2ef21b9243558/test/rmq/test_process_comms.py#L197
failed occasionally.

This might be a subtle problem which cause record remain in RabbitMQ even the aiida's process was killed? 

Failed when python=2.7 on travis.(https://travis-ci.org/unkcpz/plumpy/jobs/539049124)
Failed when python=3.4 once.

**Comment by ltalirz** [comment]
Very interesting... @muhrin any ideas?

**Comment by sphuber** [comment]
Fixed in PR #110
