### ISSUE TITLE
No longer able to expose nested inputs with `include`

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/plumpy#119]
I think there is a problem when using the `include` options in #116 
For example, in the `define` if I use:

```
def SomeWorkChain:
    @classmethod
    def define(cls, spec):
        self.expose_inputs(SomeCalculation, namespace='calc', include=['metadata'])
```

Then the `options` under `calc.metadata` is not exposed properly. It appears to be empty and if I pass any options the validation will fail complaining `options` being non-dynamic.

Also it appears that the include is not tested in #116

**Comment by sphuber** [comment]
Confirmed. Thanks for the report @zhubonan and apologies for the inconvenience. I will try to push a fix soon.
