### ISSUE TITLE
RPC call to Process.pause does account for possibility of retuning a bool instead of Future

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/plumpy#161]
I notice that there could be a bug here (that was already there) because the RPC call that's made ends up in `Process.pause()` which, if you look at, can return a boolean if the process is terminated or already paused.  Only if that's not the case will it return a future.

_Originally posted by @muhrin in https://github.com/aiidateam/plumpy/pull/150_

**Comment by unkcpz** [comment]
I guess this could be the underlying cause of process paused proxying problem in aiida_core https://github.com/aiidateam/aiida-core/issues/3694 ?

**Comment by muhrin** [comment]
There could be a connection to 3694, however I can't quite see the code path that would end up in that situation.  I would mainly expect this manifest by giving unexpected behaviour when pausing a process that is already paused (like perhaps being stuck or timing out when calling pause again).

In any case, I suggest we fix this and then reference it in 3694 to make sure it's not forgotten about.  My suggestion here would actually be to make `Process.pause()` always return a `Future` and if it's already paused then the future just has a `True` value set straight away.  

Polymorphic return types are amost always a pain and should be avoided, exactly for reasons such as that highlighted by this issue.  The downside here is that we break the public API so we need to be bit diligent on tracking down all callers of `pause`.

**Comment by unkcpz** [comment]
The `pause` and `kill` method of `Process` class can either return a `bool`  or a `asyncio.Future` just as indicated in their type hint. They will return the Future since the interrupt action is scheduled in the event loop and then finished after a while.
