### ISSUE TITLE
Relax version requirements on `aio-pika`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/plumpy#170]
Currently it is defined as `aio-pika~=6.6.1` but is it really necessary to restrict to the minor version? Same goes for `nest_asyncio`. `aiida-core` specifies `aio-pika~=6.6` which makes more sense and so it can install the released `aio-pika==6.7` but this will cause exceptions of incompatible requirements.

**Comment by sphuber** [comment]
@muhrin @unkcpz any objections to relaxing the requirement to `aio-pika~=6.6`?

**Comment by muhrin** [comment]
All good to relax on my part.  Might need to be a bit more careful with `nest_asyncio` because of the contribution that @unkcpz made, but he can comment more on that.

**Comment by unkcpz** [comment]
Changes to nest_asyncio released as v1.4.0, so only need to keep that as minimal release version. As for aio-pika, it is good to relax I think.

**Comment by sphuber** [comment]
Fixed in PR #171
