### ISSUE TITLE
drop frozendict dependency

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/plumpy#203]
We depend on frozendict; now
- this package has been unmaintained for years, and now it raises issues with python 3.8 and will not work anymore in python 3.10 (see @greschd 's [comment](https://github.com/aiidateam/aiida-core/issues/4302#issuecomment-775031129), as well ad [this PR](https://github.com/slezica/python-frozendict/pull/30) from over 1year ago and the various discussions on forking it etc.)
- the package is just a 64-line code, some of which can be removed if py2 support is not needed.
- this affects AiiDA, see aiidateam/aiida-core#4723
 
Seems various efforts of making a new release seem to be going on for quite some time but with partial success, I simply suggest to copy-paste the implementation in plumpy, fix the `collections` import to `collections.abc`, and acknowledge the original author in plumpy's licence file (frozendict is MIT).
In this way it's also 1 dependency less which is always good.

Pinging @csadorf as this needs to be reflected in the AiiDA dependencies later, @chrisjsewell who might implement this?

**Comment by chrisjsewell** [comment]
sounds good to me 👍
