### ISSUE TITLE
All Python 3.6 installs are broken

### ISSUE THREAD

**Issue by sphuber** [aiidateam/plumpy#217]
The problem is that for Python 3.6, `plumpy==0.15.1` gets installed as that is the last version to support that Python version. That `plumpy` version still uses the `frozendict` library to implement its `FrozenDict` class, which is mostly used as subclass for the `AttributesFrozenDict` which in turns is used to wrap the inputs of a process in before returning it in `self.inputs`. This is to make sure they cannot be mutated during the process running code, such as in a workchain, which would be bad. Anyway, in `frozendict==1.2` the `__setattr__` method was callable and this is actually called in `plumpy` here:

https://github.com/aiidateam/plumpy/blob/7be3b8efaef7350ee32aae4be966db32f95156ec/plumpy/utils.py#L110

However, in `frozendict==2.0` they added this line:
https://github.com/Marco-Sulla/python-frozendict/blob/e2b59b190ee77c3d7bdb1f2cd772c0b531694a4c/frozendict/core.py#L160

So now that `self._initialized = True` call in the constructor of `AttributesFrozenDict` causes the exception.

I think we should release a `v0.15.2` for plumpy that restricts the version of `frozendict<2.0`. Otherwise all new installations with Python 3.6 will be broken meaning all versions `aiida-core<1.6` will be broken.

**Comment by dev-zero** [comment]
Might be a good idea to carry 3.6 a bit longer since RHEL 8.0 (with 8.2 having 3.8 and 8.1 supported until end of 2021), openSUSE LEAP 15.2, Ubuntu 18.04 (supported until 2023) are all on Python 3.6.

**Comment by sphuber** [comment]
Fixed by #218 and released in `v0.15.2`
