### ISSUE TITLE
Continuous deployment fails 

### ISSUE THREAD

**Issue by khsrali** [aiidateam/plumpy#303]
CD fails
https://github.com/aiidateam/plumpy/actions/runs/12412762366

probably after changes of PR https://github.com/aiidateam/plumpy/pull/289

@unkcpz can we investigate this (?) the problem is I cannot reproduce it locally, even though with the same python version.. 3.8 So I'm puzzled

**Comment by sphuber** [comment]
Seems that CI pre-commit is now run with Python 3.12 but CD is still using 3.8. This is bound to give discrepancies. I would simply try to update the CD env to be the exact same of the CI.
