### ISSUE TITLE
SavableFuture is not compatible with tornado 5

### ISSUE THREAD

**Issue by muhrin** [aiidateam/plumpy#72]
Tornado 5 uses asyncio's futures while SavableFuture expects a certain internal structure to the Futures themselves and therefore uses private members (`_done`, `_result`, etc).  It should not use these and therefore will have to rely on calling the constructor and using public methods to recreate the state on `load_instance_state`.  Currently this isn't supported so we need to add this support to `Savable`.

**Comment by merkys** [comment]
I noticed Tornado 6 has been released since. I wonder what is the compatibility situation given the new stable release?

**Comment by sphuber** [comment]
We are actually in the process of moving away completely from `tornado` and use the `asyncio` standard module instead. So this should no longer be a problem after PR #150 gets merged

**Comment by merkys** [comment]
Great, I am really looking up to that!

**Comment by muhrin** [comment]
@sphuber , @unkcpz : we can close this now, right?

**Comment by unkcpz** [comment]
Sure! Please do it. @muhrin

**Comment by muhrin** [comment]
Fixed by #150.
